"""Build the Word (.docx) report from the BIHSO template + experiment results.

Run with::

    python -m src.build_docx

Produces ``Sprawozdanie.docx`` in the project root, reusing the title page and
styling of ``Wzór.docx`` and embedding the figures generated by the
experiment pipeline (``report/figures``) plus result tables read from
``results/metrics``.
"""
from __future__ import annotations

import json
from pathlib import Path

from .docx_builder import ReportBuilder

ROOT = Path(__file__).resolve().parents[1]
TEMPLATE = ROOT / "report" / "Wzór.docx"
FIGURES = ROOT / "report" / "figures"
METRICS = ROOT / "results" / "metrics" / "results_summary.json"
DATASET = ROOT / "results" / "metrics" / "dataset_summary.json"
OUTPUT = ROOT / "Sprawozdanie.docx"

WORK_TITLE = ("Porównanie skuteczności metod uczenia głębokiego i lasów "
              "losowych w prognozowaniu naruszeń danych w chmurze")

# Display order of the models throughout the document.
MODEL_ORDER = ["Logistic Regression", "Random Forest", "MLP", "CNN 1D", "LSTM"]
MODEL_PL = {
    "Logistic Regression": "Regresja logistyczna",
    "Random Forest": "Las losowy",
    "MLP": "MLP",
    "CNN 1D": "CNN 1D",
    "LSTM": "LSTM",
}


def pl(x: float, nd: int = 3) -> str:
    """Format a number with a Polish decimal comma."""
    return f"{x:.{nd}f}".replace(".", ",")


def thousand(n: int) -> str:
    return f"{n:,}".replace(",", "\u00a0")


def load_data() -> tuple[dict, dict]:
    metrics = json.loads(METRICS.read_text(encoding="utf-8"))
    dataset = json.loads(DATASET.read_text(encoding="utf-8"))
    return metrics, dataset


# ---------------------------------------------------------------------------
# Section writers
# ---------------------------------------------------------------------------
def write_streszczenie(b: ReportBuilder, m: dict, d: dict) -> None:
    b.h2("Streszczenie")
    n_total = d["n_train"] + d["n_val"] + d["n_test"]
    b.para(
        "Coraz większa część danych przetwarzanych przez organizacje trafia do "
        "chmury obliczeniowej, co czyni ją atrakcyjnym celem ataków prowadzących "
        "do naruszeń danych. Celem niniejszej pracy jest porównanie skuteczności "
        "dwóch rodzin metod uczenia maszynowego w zadaniu wykrywania (prognozowania) "
        "takich naruszeń: klasycznego lasu losowego oraz sieci głębokich "
        "(perceptronu wielowarstwowego MLP, sieci konwolucyjnej CNN oraz sieci "
        "rekurencyjnej LSTM). Zadanie sformułowano jako klasyfikację połączeń "
        "sieciowych na ruch normalny i złośliwy."
    )
    b.para(
        "W ramach pracy zbudowano kompletny, powtarzalny program w języku Python, "
        "który wczytuje dane, przygotowuje je, trenuje wszystkie modele oraz "
        "porównuje ich skuteczność i koszt obliczeniowy. Eksperyment przeprowadzono "
        f"na wycinku zbioru CSE-CIC-IDS2018 liczącym {thousand(n_total)} połączeń "
        f"opisanych {d['n_features']} cechami i należących do {len(d['class_names'])} "
        "klas, zebranych w infrastrukturze chmurowej."
    )
    best_f1 = max(m, key=lambda k: m[k]["metrics"]["f1"])
    rf = m["Random Forest"]["metrics"]
    b.para(
        f"Wyniki pokazują, że najlepszy model głęboki ({best_f1}, F1 = "
        f"{pl(m[best_f1]['metrics']['f1'])}) oraz las losowy (F1 = {pl(rf['f1'])}) "
        "osiągają niemal identyczną skuteczność, jednak las losowy uczy się "
        "kilkadziesiąt razy szybciej i pozostaje czytelny dla analityka. Bardziej "
        "rozbudowane sieci (CNN, LSTM) nie przyniosły wyraźnej przewagi, co czyni "
        "las losowy najlepszym kompromisem między skutecznością a kosztem."
    )
    b.para(
        "Słowa kluczowe: bezpieczeństwo chmury, naruszenie danych, wykrywanie "
        "ataków, uczenie maszynowe, las losowy, sieci głębokie, CSE-CIC-IDS2018.",
        justify=False,
    )


def write_wstep(b: ReportBuilder) -> None:
    b.h2("Wstęp")

    b.h3("Motywacja")
    b.para(
        "Trudno dziś wyobrazić sobie organizację, która nie korzysta z chmury "
        "obliczeniowej. Poczta, dokumenty, bazy danych i całe aplikacje coraz "
        "częściej działają na serwerach wynajmowanych od dostawców takich jak "
        "Amazon Web Services, Microsoft Azure czy Google Cloud. Wraz z usługami do "
        "chmury trafiają jednak dane, w tym te najbardziej wrażliwe, co sprawia, że "
        "staje się ona łakomym celem dla cyberprzestępców. Naruszenie danych, czyli "
        "ich wyciek lub kradzież, należy do najbardziej kosztownych incydentów "
        "bezpieczeństwa, a jego wykrycie często następuje dopiero po wielu "
        "tygodniach od momentu włamania."
    )
    b.para(
        "Klasyczne, sygnaturowe systemy ochrony coraz słabiej radzą sobie z nowymi, "
        "nieznanymi wcześniej atakami oraz z ogromną skalą i zmiennością ruchu w "
        "chmurze. Z tego powodu dużą rolę odgrywają metody uczenia maszynowego, "
        "które potrafią samodzielnie uczyć się rozpoznawania złośliwej aktywności "
        "na podstawie danych historycznych. Wśród nich szczególne miejsce zajmują "
        "dwa podejścia: klasyczne lasy losowe oraz nowsze uczenie głębokie. Oba "
        "regularnie osiągają czołowe wyniki, lecz różnią się złożonością, kosztem i "
        "łatwością interpretacji decyzji."
    )

    b.h3("Cel i zakres pracy")
    b.para(
        "Celem pracy jest empiryczne porównanie skuteczności metod uczenia "
        "głębokiego i lasów losowych w zadaniu prognozowania naruszeń danych w "
        "chmurze. Przez prognozowanie naruszenia rozumiemy rozpoznawanie "
        "pojedynczych połączeń sieciowych jako normalnych albo złośliwych, "
        "ponieważ wykrycie podejrzanego połączenia stanowi wczesne ostrzeżenie "
        "przed pełnym wyciekiem danych."
    )
    b.para("Praca odpowiada na trzy pytania badawcze:")
    b.bullets([
        "Które podejście, las losowy czy sieci głębokie, skuteczniej wykrywa ataki?",
        "Jaki jest koszt obliczeniowy obu podejść i czy wyższa skuteczność jest "
        "warta tego kosztu?",
        "Czy bardziej rozbudowane sieci (CNN, LSTM) są lepsze od prostej sieci MLP "
        "na danych opisujących ruch sieciowy?",
    ])

    b.h3("Znaczenie problemu")
    b.para(
        "Skala zjawiska sprawia, że temat jest istotny zarówno z perspektywy "
        "biznesowej, jak i inżynierskiej. Pojedyncze naruszenie danych potrafi "
        "kosztować organizację miliony złotych, licząc koszty bezpośrednie (analiza "
        "incydentu, powiadomienia, kary regulacyjne) oraz pośrednie (utrata reputacji "
        "i klientów). Dodatkowo czas od włamania do jego wykrycia bywa bardzo długi, "
        "co oznacza, że atakujący mają wiele czasu na wyrządzenie szkód. Każde "
        "rozwiązanie skracające ten czas, nawet o kilka godzin, ma więc realną "
        "wartość. Automatyczne wykrywanie podejrzanego ruchu jest jednym z "
        "najtańszych i najszybciej skalujących się sposobów osiągnięcia tego celu, a "
        "jego skuteczność zależy wprost od jakości zastosowanego modelu uczenia "
        "maszynowego, co czyni porównanie metod tematem o praktycznym znaczeniu."
    )

    b.h3("Układ dokumentu")
    b.para(
        "Dokument ma układ typowy dla krótkiej pracy inżynierskiej. Po wstępie "
        "przybliżono tematykę i kontekst bezpieczeństwa chmury, następnie opisano "
        "sam problem, uzasadniono wybór metod, przedstawiono realizację praktyczną "
        "wraz z wynikami, omówiono je w osobnym rozdziale dyskusji, a na końcu "
        "sformułowano wnioski. Wszystkie liczby i wykresy zawarte w pracy pochodzą "
        "bezpośrednio z napisanego programu, dzięki czemu treść jest spójna z "
        "faktycznymi wynikami eksperymentu."
    )


def write_tematyka(b: ReportBuilder) -> None:
    b.h2("Tematyka i kontekst")

    b.h3("Chmura obliczeniowa")
    b.para(
        "Chmura obliczeniowa to model dostarczania zasobów informatycznych "
        "(mocy obliczeniowej, pamięci, baz danych, aplikacji) jako usługi "
        "dostępnej przez sieć. Zamiast utrzymywać własne serwerownie, organizacje "
        "wynajmują zasoby od dostawcy i płacą za ich rzeczywiste wykorzystanie. "
        "Wygoda i oszczędność mają jednak swoją cenę: dane wielu klientów żyją na "
        "współdzielonej infrastrukturze, dostępnej zdalnie z dowolnego miejsca na "
        "świecie, a powierzchnia ataku znacząco rośnie."
    )

    b.h3("Modele usług chmurowych")
    b.para(
        "Chmura dostarczana jest w kilku modelach usługowych, które różnią się "
        "zakresem odpowiedzialności klienta. W modelu IaaS (infrastruktura jako "
        "usługa) klient otrzymuje maszyny wirtualne i sieć, samodzielnie zarządzając "
        "systemem operacyjnym i aplikacjami. W modelu PaaS (platforma jako usługa) "
        "dostawca zarządza również środowiskiem uruchomieniowym, a klient skupia się "
        "na własnym kodzie. W modelu SaaS (oprogramowanie jako usługa) klient "
        "korzysta z gotowej aplikacji przez przeglądarkę. Niezależnie od modelu, "
        "komunikacja sieciowa pozostaje wspólnym mianownikiem i nośnikiem śladów "
        "potencjalnych ataków, dlatego analiza ruchu sieciowego jest uniwersalnym "
        "punktem zaczepienia dla mechanizmów wykrywania naruszeń."
    )

    b.h3("Model współdzielonej odpowiedzialności")
    b.para(
        "Bezpieczeństwo w chmurze opiera się na tzw. modelu współdzielonej "
        "odpowiedzialności. Dostawca chmury odpowiada za bezpieczeństwo samej "
        "infrastruktury (centra danych, sprzęt, wirtualizacja), natomiast za "
        "poprawną konfigurację usług, kontrolę dostępu i ochronę własnych danych "
        "odpowiada klient. W praktyce ogromna część głośnych wycieków danych "
        "wynikała nie z włamania do serwerów dostawcy, lecz z błędów po stronie "
        "użytkownika: źle ustawionych uprawnień, publicznie dostępnych zasobów czy "
        "przejętych kont. To pokazuje, że samo przeniesienie danych do chmury nie "
        "zwalnia organizacji z obowiązku ich monitorowania."
    )

    b.h3("Rola uczenia maszynowego w cyberbezpieczeństwie")
    b.para(
        "Skala i zmienność ruchu sieciowego w chmurze są tak duże, że ręczne "
        "pilnowanie bezpieczeństwa przestaje być możliwe. Uczenie maszynowe pozwala "
        "zautomatyzować ten proces: model uczy się rozpoznawać wzorce złośliwej "
        "aktywności na podstawie historycznych przykładów, a następnie klasyfikuje "
        "nowy ruch w czasie zbliżonym do rzeczywistego. W odróżnieniu od metod "
        "sygnaturowych, modele uczenia maszynowego potrafią uogólniać i wykrywać "
        "również warianty ataków, których wcześniej nie widziały. To właśnie czyni "
        "je obiecującym narzędziem w ochronie danych w chmurze i uzasadnia ich "
        "porównanie podjęte w tej pracy."
    )


def write_problem(b: ReportBuilder, d: dict) -> None:
    b.h2("Opis problemu")

    b.h3("Naruszenia danych w chmurze i ich typy")
    b.para(
        "Naruszenie danych to sytuacja, w której dane trafiają w niepowołane ręce: "
        "zostają wykradzione, ujawnione lub zmienione bez uprawnienia. Konsekwencje "
        "bywają dotkliwe, od kar finansowych (np. na gruncie RODO), przez utratę "
        "zaufania klientów, po realne straty operacyjne. W środowisku chmurowym "
        "najczęstsze drogi prowadzące do naruszenia obejmują:"
    )
    b.bullets([
        "przejęcie kont, np. zgadywanie haseł metodą brute force do usług logowania;",
        "eksfiltrację danych, czyli niepostrzeżone wyprowadzanie danych na zewnątrz, "
        "często ukryte w pozornie zwykłym ruchu;",
        "ataki DoS/DDoS, zalewające usługi ruchem, czasem jako zasłona dymna dla "
        "innych działań;",
        "infiltrację i ruch boczny, gdy po zdobyciu przyczółka atakujący przemieszcza "
        "się w infrastrukturze ofiary;",
        "aktywność botnetów oraz ataki na aplikacje webowe (np. SQL injection), "
        "również prowadzące do wycieku danych.",
    ])
    b.para(
        "Wszystkie te działania mają jedną wspólną cechę: zostawiają ślad w ruchu "
        "sieciowym. Analiza tego ruchu pozwala wychwycić podejrzaną aktywność, "
        "zanim przerodzi się ona w pełne naruszenie."
    )

    b.h3("Przykładowy scenariusz naruszenia")
    b.para(
        "Aby zilustrować problem, rozważmy typowy scenariusz. Atakujący najpierw "
        "skanuje publicznie dostępne usługi chmurowe ofiary, poszukując otwartych "
        "portów. Następnie próbuje uzyskać dostęp do usługi zdalnego logowania, "
        "wielokrotnie zgadując hasła (atak brute force). Po przejęciu konta loguje "
        "się i rozpoczyna rozpoznanie wewnętrzne, a w końcu kopiuje dane na zewnętrzny "
        "serwer. Na każdym z tych etapów powstaje charakterystyczny ruch sieciowy: "
        "wiele krótkich połączeń podczas skanowania, liczne nieudane próby logowania, "
        "nietypowe połączenia wychodzące podczas eksfiltracji. Model klasyfikujący "
        "połączenia ma szansę wychwycić każdy z tych etapów, dając zespołowi "
        "bezpieczeństwa czas na reakcję, zanim dojdzie do faktycznej utraty danych."
    )

    b.h3("Sformułowanie zadania klasyfikacji")
    b.para(
        "Naruszenie danych rzadko jest pojedynczym zdarzeniem; to zwykle finał "
        "całego łańcucha działań: rozpoznania, włamania, eskalacji uprawnień i "
        "wreszcie kradzieży danych. Wykrycie wczesnych ogniw tego łańcucha pełni "
        "rolę prognostyczną, bo pozwala zareagować, zanim dojdzie do wycieku. "
        "Dlatego prognozowanie naruszenia utożsamiamy z rozpoznawaniem złośliwych "
        "połączeń sieciowych."
    )
    b.para(
        "Zadanie sprowadza się do prostego pytania zadawanego dla każdego "
        "połączenia: czy to zwykły, normalny ruch, czy raczej atak? Każde "
        "połączenie opisujemy zestawem liczb, na przykład jak długo trwało, ile "
        "pakietów i bajtów przesłano, jak często czy jakie flagi sieciowe się "
        "pojawiły. Na tej podstawie model przykleja jedną z dwóch etykiet: ruch "
        "normalny albo atak. Jest to więc klasyczne zadanie klasyfikacji binarnej; "
        "ponieważ dane zawierają też informację o rodzaju ataku, możliwa jest "
        "dodatkowo analiza poszczególnych typów zagrożeń."
    )

    b.h3("Wyzwania")
    b.para("Wykrywanie naruszeń nie jest proste z kilku praktycznych powodów:")
    b.bullets([
        "Ataki są rzadkie. W normalnym ruchu tonie garstka złośliwych połączeń, "
        "przez co model łatwo wpada w pułapkę uznawania wszystkiego za normalne i "
        "przeocza zagrożenia.",
        "Nie każdy błąd kosztuje tyle samo. Przeoczenie ataku jest zwykle znacznie "
        "groźniejsze niż fałszywy alarm, dlatego zależy nam przede wszystkim na "
        "wysokiej wykrywalności.",
        "Złośliwość kryje się w kombinacjach cech. Pojedyncza cecha rzadko zdradza "
        "atak; dopiero ich zestawienie tworzy podejrzany obraz, co wyklucza "
        "najprostsze metody liniowe.",
        "Liczy się szybkość i koszt. W chmurze model trzeba często dotrenowywać i "
        "stosować na bieżąco do ogromnych ilości ruchu, więc nie może być zbyt "
        "kosztowny obliczeniowo.",
    ])


def write_podejscie(b: ReportBuilder) -> None:
    b.h2("Uzasadnienie wybranego podejścia")

    b.h3("Dlaczego porównanie lasu losowego z sieciami głębokimi")
    b.para(
        "Spośród wielu metod uczenia maszynowego do porównania wybrano dwie "
        "najpopularniejsze i jednocześnie reprezentatywne rodziny. Las losowy to "
        "sprawdzona, klasyczna technika, która w zadaniach wykrywania intruzji "
        "wielokrotnie osiągała czołowe wyniki przy niewielkim koszcie. Uczenie "
        "głębokie reprezentuje natomiast nowoczesny nurt, który zrewolucjonizował "
        "analizę obrazów, dźwięku i tekstu. Zestawienie tych dwóch podejść pozwala "
        "odpowiedzieć na praktyczne pytanie: czy w ochronie danych w chmurze warto "
        "sięgać po skomplikowane sieci neuronowe, czy wystarczy dobrze dobrana "
        "metoda klasyczna."
    )

    b.h3("Ograniczenia metod sygnaturowych")
    b.para(
        "Tradycyjne systemy wykrywania włamań opierają się na sygnaturach, czyli "
        "wzorcach znanych ataków. Działają one dobrze, dopóki zagrożenie jest znane, "
        "lecz zawodzą wobec nowych wariantów, których sygnatury jeszcze nie "
        "powstały. W chmurze, gdzie ruch jest ogromny i zmienny, a atakujący stale "
        "modyfikują techniki, podejście sygnaturowe staje się niewystarczające. "
        "Uczenie maszynowe uzupełnia tę lukę, ucząc się ogólnych cech złośliwej "
        "aktywności zamiast zapamiętywać pojedyncze wzorce, dzięki czemu potrafi "
        "rozpoznać również nieznane wcześniej zagrożenia o podobnym charakterze."
    )

    b.h3("Las losowy")
    b.para(
        "Punktem wyjścia jest drzewo decyzyjne, które można sobie wyobrazić jako "
        "listę pytań typu: czy liczba pakietów w połączeniu przekracza pewien próg? "
        "Odpowiadając na kolejne pytania, schodzimy w dół drzewa aż do liścia, który "
        "mówi, czy to ruch normalny, czy atak. Pojedyncze drzewo jest jednak "
        "kapryśne i łatwo się przeucza. Las losowy rozwiązuje ten problem prostą "
        "sztuczką: zamiast jednego drzewa buduje ich setki, a każde uczy na nieco "
        "innym, losowym wycinku danych i cech. Decyzja końcowa zapada przez "
        "głosowanie, dzięki czemu wynik jest znacznie stabilniejszy. Las losowy nie "
        "wymaga skalowania danych, dobrze radzi sobie ze złożonymi zależnościami, "
        "szybko się uczy i potrafi wskazać, które cechy były najważniejsze przy "
        "podejmowaniu decyzji."
    )

    b.h3("Sieci głębokie")
    b.para(
        "Sieć neuronowa to model luźno inspirowany działaniem mózgu, złożony z "
        "warstw neuronów. Każdy neuron łączy informacje z poprzedniej warstwy, mnoży "
        "je przez wyuczone wagi i przepuszcza przez nieliniową funkcję aktywacji. "
        "Określenie głęboka oznacza, że warstw jest wiele, dzięki czemu sieć "
        "stopniowo buduje coraz bardziej złożone wzorce: od prostych zależności po "
        "abstrakcyjne sygnatury złośliwej aktywności. Uczenie polega na wielokrotnym "
        "pokazywaniu sieci przykładów i korygowaniu wag metodą wstecznej propagacji "
        "błędu tak, aby sieć coraz rzadziej się myliła. W pracy porównano trzy "
        "architektury:"
    )
    b.bullets([
        "MLP (perceptron wielowarstwowy) to najprostsza sieć w pełni połączona, "
        "traktująca dane jak zwykłą tabelę liczb; jest naturalnym wyborem dla danych "
        "o połączeniach sieciowych.",
        "CNN 1D (sieć konwolucyjna) przesuwa okienko po danych i wyszukuje "
        "powtarzające się, lokalne wzorce; sprawdza się w analizie sygnałów.",
        "LSTM (sieć rekurencyjna) ma pamięć i jest zaprojektowana do danych o "
        "charakterze sekwencji; włączono ją, aby sprawdzić, czy modelowanie "
        "sekwencyjności cech przynosi korzyść.",
    ])

    b.h3("Miary oceny skuteczności")
    b.para(
        "Sama dokładność, czyli odsetek poprawnych decyzji, bywa myląca, gdy ataki "
        "są rzadkie: model uznający wszystko za ruch normalny może mieć wysoką "
        "dokładność, a jednocześnie nie wykryć żadnego włamania. Dlatego oceniamy "
        "modele kilkoma uzupełniającymi się miarami:"
    )
    b.bullets([
        "Precyzja: spośród połączeń oznaczonych jako atak, jaki odsetek faktycznie "
        "był atakiem. Niska precyzja oznacza wiele fałszywych alarmów.",
        "Czułość: spośród wszystkich prawdziwych ataków, ile udało się wykryć. Niska "
        "czułość oznacza przeoczone włamania, czyli najgroźniejszy rodzaj błędu.",
        "F1: jedna liczba godząca precyzję i czułość, wygodna do porównań.",
        "ROC-AUC i PR-AUC: miary jakości niezależne od ustawionego progu "
        "decyzyjnego; im bliżej jedności, tym lepiej.",
    ])
    b.para(
        "W kontekście ochrony danych w chmurze szczególnie zależy nam na wysokiej "
        "czułości, aby nie przeoczyć naruszenia, przy rozsądnej precyzji, aby nie "
        "zasypać analityków fałszywymi alarmami."
    )

    b.h3("Przegląd literatury")
    b.para(
        "Wykrywanie włamań metodami uczenia maszynowego to dobrze zbadany temat. "
        "Powszechnie wykorzystuje się publiczne zbiory danych, takie jak NSL-KDD, "
        "UNSW-NB15 czy CIC-IDS2017 i CSE-CIC-IDS2018 przygotowane przez Canadian "
        "Institute for Cybersecurity. W wielu badaniach metody oparte na drzewach, "
        "jak las losowy, okazują się równie dobre lub lepsze od sieci głębokich, gdy "
        "dane mają postać tabeli, a tak właśnie wyglądają cechy połączeń sieciowych. "
        "Sieci głębokie błyszczą przede wszystkim tam, gdzie dane są surowe i mają "
        "wyraźną strukturę przestrzenną lub czasową. Niniejsza praca sprawdza, czy "
        "ta obserwacja potwierdza się również w analizowanym zadaniu chmurowym."
    )


def write_realizacja(b: ReportBuilder, d: dict) -> None:
    b.h2("Realizacja zadania")

    b.h3("Ogólny schemat eksperymentu")
    b.para(
        "Aby porównanie było uczciwe, wszystkie modele uczono i testowano na tych "
        "samych danych oraz oceniano tymi samymi miarami. Eksperyment przebiega "
        "według prostego scenariusza: wczytanie danych, ich przygotowanie, "
        "wytrenowanie pięciu modeli (regresji logistycznej, lasu losowego oraz "
        "sieci MLP, CNN i LSTM), ocena każdego z nich pod kątem skuteczności i "
        "kosztu, a na końcu zebranie wyników w postaci tabel i wykresów."
    )

    b.h3("Zbiór danych")
    n_total = d["n_train"] + d["n_val"] + d["n_test"]
    b.para(
        "Głównym zbiorem danych jest CSE-CIC-IDS2018, duży, publicznie dostępny "
        "zbiór ruchu sieciowego zebranego na chmurowej infrastrukturze AWS przez "
        "Canadian Institute for Cybersecurity. Zawiera on zarówno ruch normalny, "
        "jak i różne typy ataków (m.in. łamanie haseł, DoS/DDoS, ataki na aplikacje "
        "webowe, infiltrację oraz botnety). Każde połączenie opisane jest "
        "kilkudziesięcioma cechami liczbowymi, takimi jak czas trwania, liczba i "
        "rozmiar przesłanych pakietów, tempo transmisji czy liczniki flag sieciowych."
    )
    b.para(
        "Pełny zbiór waży kilka gigabajtów (same pliki dzienne to łącznie około 7 "
        "GB), dlatego program wczytuje go w częściach i losowo próbkuje, biorąc "
        "porcję danych z każdego dnia, ponieważ każdy dzień zawiera inne typy "
        "ataków. Ostatecznie wykorzystano wycinek liczący "
        f"{thousand(n_total)} połączeń opisanych {d['n_features']} cechami i "
        f"należących do {len(d['class_names'])} klas (ruch normalny oraz "
        f"{len(d['class_names']) - 1} typów ataków). Należy podkreślić, że jest to "
        "reprezentatywny wycinek połączonych plików, a nie pojedynczy plik ani "
        "komplet danych w całości. Dla zachowania pełnej powtarzalności program "
        "potrafi też w razie potrzeby skorzystać z wbudowanego generatora danych "
        "syntetycznych o zbliżonej charakterystyce."
    )
    b.para(
        "Rysunek 1 przedstawia rozkład klas. Widoczna jest wyraźna przewaga ruchu "
        "normalnego nad atakami, typowa dla zadań wykrywania zagrożeń, oraz duża "
        "rzadkość niektórych typów ataków (np. SQL Injection), co stanowi istotne "
        "wyzwanie dla modeli."
    )
    b.figure(FIGURES / "class_distribution.png",
             "Rysunek 1. Rozkład klas w wykorzystanym wycinku zbioru CSE-CIC-IDS2018.",
             width_cm=13.5)

    b.h3("Przetwarzanie wstępne danych")
    b.para("Surowe dane wymagają uporządkowania. Etap przygotowania obejmuje:")
    b.bullets([
        "usunięcie kolumn nieprzydatnych do klasyfikacji (adresy IP, porty, "
        "znaczniki czasu) oraz kolumn o stałej wartości;",
        "poprawienie brakujących i błędnych wartości, np. wartości nieskończonych "
        "powstających przy dzieleniu;",
        "zamianę etykiet na prostą postać: ruch normalny lub atak;",
        "ujednolicenie skali cech, tak aby duże liczby nie zagłuszały mniejszych, co "
        "jest ważne zwłaszcza dla sieci neuronowych;",
        "podział danych na trzy części: uczącą, walidacyjną i testową.",
    ])
    b.para(
        "Podział wykonano z ustalonym ziarnem losowości, dzięki czemu wyniki są w "
        f"pełni powtarzalne. Liczności zbiorów wynoszą: {thousand(d['n_train'])} "
        f"(uczący), {thousand(d['n_val'])} (walidacyjny) oraz {thousand(d['n_test'])} "
        "(testowy) połączeń."
    )
    b.para(
        "Podział na trzy zbiory pełni ważną rolę metodologiczną. Zbiór uczący służy "
        "do dopasowania modelu, zbiór walidacyjny do kontrolowania przebiegu uczenia "
        "i decyzji o jego zatrzymaniu, a zbiór testowy, którego model nigdy nie widzi "
        "podczas treningu, do uczciwej, końcowej oceny. Podział jest stratyfikowany, "
        "co oznacza, że proporcje ruchu normalnego i ataków są w każdym z podzbiorów "
        "zbliżone do proporcji w całym zbiorze. Dzięki temu ocena nie jest "
        "zafałszowana przez przypadkowy nadmiar lub niedobór ataków w którymś z "
        "podzbiorów."
    )

    b.h3("Konfiguracja modeli")
    b.para("Porównano pięć modeli o rosnącej złożoności:")
    b.bullets([
        "Regresja logistyczna: prosty model liniowy, traktowany jako punkt "
        "odniesienia; pokazuje, ile zyskujemy, sięgając po metody zaawansowane.",
        "Las losowy: zespół 300 drzew decyzyjnych z ważeniem klas.",
        "MLP: sieć z dwiema warstwami ukrytymi (128 i 64 neurony).",
        "CNN 1D: sieć konwolucyjna z dwiema warstwami filtrów.",
        "LSTM: dwukierunkowa sieć rekurencyjna.",
    ])
    b.para(
        "Aby uczciwie potraktować rzadkość ataków, w każdym modelu zastosowano "
        "mechanizmy równoważące klasy, dzięki którym model jest mocniej karany za "
        "przeoczenie ataku. Sieci głębokie uczono z wykorzystaniem wczesnego "
        "zatrzymania: nauka kończy się, gdy model przestaje się poprawiać na danych "
        "walidacyjnych, co zapobiega przeuczeniu."
    )

    b.h3("Środowisko i narzędzia")
    b.para(
        "Całość zaimplementowano w języku Python. Modele klasyczne zbudowano przy "
        "użyciu biblioteki scikit-learn, a sieci głębokie w bibliotece PyTorch "
        "(TensorFlow nie udostępnia jeszcze wersji dla używanego Pythona 3.14). "
        "Wykresy przygotowano w bibliotece matplotlib. Obliczenia prowadzono na "
        "zwykłym procesorze (CPU), co dobrze oddaje warunki ograniczonych zasobów i "
        "uwypukla różnice w koszcie między metodami. Szczegóły implementacyjne "
        "samego programu opisano w osobnym rozdziale."
    )


def write_implementacja(b: ReportBuilder) -> None:
    b.h2("Implementacja programu")
    b.para(
        "Niniejszy rozdział opisuje szczegóły implementacyjne programu napisanego na "
        "potrzeby eksperymentu. Całość powstała w języku Python i została podzielona "
        "na niezależne moduły o jasno określonej odpowiedzialności, co ułatwia "
        "zrozumienie kodu, jego testowanie oraz rozszerzanie o nowe modele i zbiory "
        "danych."
    )

    b.h3("Organizacja kodu")
    b.para(
        "Kod źródłowy znajduje się w katalogu src i jest zorganizowany w pakiety "
        "odpowiadające kolejnym etapom potoku przetwarzania. Strukturę katalogów "
        "przedstawia poniższy listing."
    )
    b.code_block(
        "src/\n"
        "  config.py          # parametry eksperymentu (dataklasy)\n"
        "  utils.py           # ziarno losowości, pomiar czasu, zapis JSON\n"
        "  data/\n"
        "    synthetic.py     # generator danych syntetycznych\n"
        "    download.py      # wczytywanie wycinka CSE-CIC-IDS2018\n"
        "    loader.py        # wybor zrodla danych (auto/cicids/synthetic)\n"
        "    preprocess.py    # czyszczenie, kodowanie, podzial, skalowanie\n"
        "  models/\n"
        "    classical.py     # las losowy i regresja logistyczna\n"
        "    deep.py          # sieci MLP, CNN 1D, LSTM (PyTorch)\n"
        "  evaluate.py        # obliczanie metryk\n"
        "  train.py           # petla treningowo-ewaluacyjna\n"
        "  plots.py           # generowanie wykresow\n"
        "  tables.py          # eksport tabel wynikow\n"
        "  run_all.py         # uruchomienie calego potoku",
        caption="Listing 1. Struktura katalogów z kodem źródłowym.",
    )

    b.h3("Konfiguracja eksperymentu")
    b.para(
        "Wszystkie parametry eksperymentu zebrano w module config w postaci klas "
        "danych (dataclass). Dzięki temu w jednym miejscu można zmienić źródło "
        "danych, liczbę drzew lasu losowego, liczbę epok uczenia sieci czy rozmiary "
        "warstw. Centralnie ustawione jest też ziarno losowości, które zapewnia "
        "powtarzalność wyników."
    )
    b.code_block(
        "@dataclass\n"
        "class RandomForestConfig:\n"
        "    n_estimators: int = 300\n"
        "    class_weight: str | None = \"balanced\"\n"
        "    n_jobs: int = -1\n\n"
        "@dataclass\n"
        "class DeepConfig:\n"
        "    epochs: int = 30\n"
        "    batch_size: int = 256\n"
        "    learning_rate: float = 1e-3\n"
        "    hidden_dim: int = 128\n"
        "    early_stopping_patience: int = 6",
        caption="Listing 2. Fragment konfiguracji modeli (config.py).",
    )

    b.h3("Pozyskiwanie i przygotowanie danych")
    b.para(
        "Moduł loader wybiera źródło danych zgodnie z konfiguracją: w trybie auto "
        "próbuje wczytać rzeczywisty zbiór, a w razie jego braku przełącza się na "
        "generator syntetyczny. Ponieważ pełny zbiór CSE-CIC-IDS2018 waży kilka "
        "gigabajtów, moduł download wczytuje pliki w częściach (chunkach) i losowo "
        "próbkuje, dzięki czemu zużycie pamięci pozostaje ograniczone niezależnie od "
        "rozmiaru plików."
    )
    b.code_block(
        "for chunk in pd.read_csv(path, chunksize=chunksize, low_memory=False):\n"
        "    chunk = _normalise_columns(chunk)\n"
        "    if 0.0 < sample_frac < 1.0:\n"
        "        chunk = chunk.sample(frac=sample_frac, random_state=seed)\n"
        "    buffer.append(chunk)",
        caption="Listing 3. Strumieniowe, oszczędne pamięciowo wczytywanie danych "
                "(download.py).",
    )
    b.para(
        "Moduł preprocess realizuje czyszczenie danych: usuwa kolumny "
        "nieinformatywne i identyfikujące, zastępuje wartości nieskończone i "
        "brakujące, binaryzuje etykietę (ruch normalny lub atak), standaryzuje cechy "
        "i dzieli dane na zbiory uczący, walidacyjny oraz testowy w sposób "
        "stratyfikowany. Skaler dopasowywany jest wyłącznie na zbiorze uczącym, aby "
        "uniknąć wycieku informacji ze zbioru testowego."
    )

    b.h3("Implementacja modeli")
    b.para(
        "Modele klasyczne (las losowy i regresja logistyczna) oparto na bibliotece "
        "scikit-learn, a sieci głębokie zaimplementowano w PyTorch. Wszystkie modele "
        "udostępniają wspólny, prosty interfejs z metodami fit oraz predict_proba, "
        "dzięki czemu pętla treningowa traktuje je jednolicie. Trzy architektury "
        "sieci (MLP, CNN 1D, LSTM) dzielą wspólną klasę opakowującą, która zarządza "
        "pętlą uczenia, ważeniem klas i wczesnym zatrzymaniem."
    )
    b.code_block(
        "class CNN1D(nn.Module):\n"
        "    def __init__(self, in_dim, hidden, dropout):\n"
        "        super().__init__()\n"
        "        self.features = nn.Sequential(\n"
        "            nn.Conv1d(1, 32, kernel_size=3, padding=1),\n"
        "            nn.BatchNorm1d(32), nn.ReLU(), nn.MaxPool1d(2),\n"
        "            nn.Conv1d(32, 64, kernel_size=3, padding=1),\n"
        "            nn.BatchNorm1d(64), nn.ReLU(),\n"
        "            nn.AdaptiveMaxPool1d(4))\n"
        "        self.classifier = nn.Sequential(\n"
        "            nn.Flatten(), nn.Linear(64 * 4, hidden),\n"
        "            nn.ReLU(), nn.Dropout(dropout), nn.Linear(hidden, 1))",
        caption="Listing 4. Definicja sieci konwolucyjnej CNN 1D (deep.py).",
    )
    b.para(
        "Niezbalansowanie klas uwzględniono na dwa sposoby: w lesie losowym przez "
        "parametr class_weight ustawiony na wartość balanced, a w sieciach głębokich "
        "przez ważenie klasy pozytywnej w funkcji straty. Uczenie sieci zatrzymywane "
        "jest automatycznie, gdy miara ROC-AUC na zbiorze walidacyjnym przestaje się "
        "poprawiać, co chroni przed przeuczeniem i skraca czas obliczeń."
    )

    b.h3("Trening, ewaluacja i wizualizacja")
    b.para(
        "Moduł train trenuje kolejno wszystkie modele na tym samym podziale danych, "
        "mierząc czas uczenia oraz czas klasyfikacji. Moduł evaluate oblicza komplet "
        "metryk (dokładność, precyzję, czułość, F1, ROC-AUC, PR-AUC) wraz z macierzą "
        "pomyłek. Moduły plots oraz tables zapisują wykresy i tabele wykorzystane w "
        "tym sprawozdaniu, dzięki czemu jego treść jest zawsze zgodna z faktycznymi "
        "wynikami."
    )

    b.h3("Generowanie sprawozdania")
    b.para(
        "Sam dokument, który właśnie czytasz, również powstaje programowo. Moduł "
        "build_docx wykorzystuje istniejący szablon dokumentu jako bazę stylów i "
        "strony tytułowej, a następnie wstawia treść, osadza wygenerowane wykresy i "
        "buduje tabele z zapisanych wyników. Pozwala to wygenerować spójne "
        "sprawozdanie jednym poleceniem."
    )

    b.h3("Sposób uruchomienia")
    b.para(
        "Cały eksperyment uruchamia się jednym poleceniem. Domyślnie program "
        "korzysta z danych rzeczywistych, jeśli są dostępne, a parametry można "
        "nadpisać argumentami wiersza poleceń."
    )
    b.code_block(
        "# pelny eksperyment (dane rzeczywiste lub syntetyczne)\n"
        "python -m src.run_all\n\n"
        "# wymuszenie danych syntetycznych i krotszy trening\n"
        "python -m src.run_all --source synthetic --epochs 10\n\n"
        "# wygenerowanie sprawozdania w formacie .docx\n"
        "python -m src.build_docx",
        caption="Listing 5. Polecenia uruchamiające eksperyment i generujące "
                "sprawozdanie.",
    )


def write_wyniki(b: ReportBuilder, m: dict) -> None:
    b.h2("Wyniki i analiza")

    b.h3("Skuteczność modeli")
    b.para(
        "Tabela 1 zestawia metryki skuteczności wszystkich modeli na zbiorze "
        "testowym, a rysunek 2 przedstawia je graficznie."
    )
    # Metrics table
    headers = ["Model", "Dokładność", "Precyzja", "Czułość", "F1", "ROC-AUC", "PR-AUC"]
    rows = []
    for k in MODEL_ORDER:
        met = m[k]["metrics"]
        rows.append([
            MODEL_PL[k], pl(met["accuracy"]), pl(met["precision"]),
            pl(met["recall"]), pl(met["f1"]), pl(met["roc_auc"]), pl(met["pr_auc"]),
        ])
    b.table(headers, rows, caption="Tabela 1. Skuteczność modeli na zbiorze testowym.",
            col_widths_cm=[3.4, 2.0, 1.9, 1.8, 1.6, 1.9, 1.8])

    best_f1 = max(m, key=lambda k: m[k]["metrics"]["f1"])
    rf = m["Random Forest"]["metrics"]
    b.para(
        "Z zestawienia wynika kilka obserwacji. Po pierwsze, wszystkie metody "
        "bardziej zaawansowane wyraźnie przewyższają prostą regresję logistyczną, "
        "co potwierdza, że atak zdradza dopiero kombinacja cech, a nie pojedyncze "
        "wartości. Po drugie, na szczycie panuje praktyczny remis: najlepszy model "
        f"głęboki {best_f1} (F1 = {pl(m[best_f1]['metrics']['f1'])}) i las losowy "
        f"(F1 = {pl(rf['f1'])}, ROC-AUC = {pl(rf['roc_auc'])}) osiągają niemal "
        "identyczne wyniki. Po trzecie, oba modele mają nieco inny charakter: las "
        "losowy uzyskuje najwyższą czułość oraz najwyższy PR-AUC, podczas gdy CNN "
        "ma najwyższą precyzję. Najbardziej rozbudowany model, sieć LSTM, wypada "
        "najsłabiej spośród metod nieliniowych mimo największej złożoności."
    )
    b.figure(FIGURES / "metrics_comparison.png",
             "Rysunek 2. Porównanie metryk skuteczności modeli na zbiorze testowym.",
             width_cm=15.0)

    b.h3("Krzywe ROC i precyzja-czułość")
    b.para(
        "Rysunki 3 i 4 przedstawiają krzywe ROC oraz precyzja-czułość. Krzywe dla "
        "wszystkich modeli nieliniowych przebiegają blisko lewego górnego rogu "
        "(ROC) i prawego górnego rogu (precyzja-czułość), co świadczy o dobrej "
        "separowalności klas. Regresja logistyczna wyraźnie odstaje, zwłaszcza na "
        "krzywej precyzja-czułość, która lepiej oddaje trudność zadania przy "
        "rzadkich atakach."
    )
    b.figure(FIGURES / "roc_curves.png", "Rysunek 3. Krzywe ROC dla porównywanych modeli.",
             width_cm=11.5)
    b.figure(FIGURES / "pr_curves.png",
             "Rysunek 4. Krzywe precyzja-czułość dla porównywanych modeli.",
             width_cm=11.5)

    b.h3("Analiza błędów")
    b.para(
        "Macierze pomyłek na rysunku 5 pozwalają zajrzeć pod maskę i zobaczyć, "
        "jakie błędy popełniają modele. Las losowy wychwytuje najwięcej ataków "
        "(najwyższa czułość), czyli rzadziej przepuszcza zagrożenie, co w kontekście "
        "ochrony danych jest cenne, bo przeoczone naruszenie kosztuje najwięcej. "
        "Sieć CNN nieco rzadziej podnosi fałszywy alarm (najwyższa precyzja), czyli "
        "mniej obciąża zespół bezpieczeństwa niepotrzebnymi powiadomieniami. W "
        "praktyce punkt równowagi między tymi błędami można regulować progiem "
        "decyzyjnym, dopasowując go do polityki bezpieczeństwa organizacji."
    )
    rf_cm = m["Random Forest"]["metrics"]["confusion_matrix"]
    cnn_cm = m["CNN 1D"]["metrics"]["confusion_matrix"]
    lstm_cm = m["LSTM"]["metrics"]["confusion_matrix"]
    b.para(
        "Konkretne liczby dobrze ilustrują te różnice. Na zbiorze testowym las "
        f"losowy przeoczył {rf_cm['fn']} ataków i wygenerował {rf_cm['fp']} fałszywych "
        f"alarmów, sieć CNN przeoczyła {cnn_cm['fn']} ataków przy zaledwie "
        f"{cnn_cm['fp']} fałszywych alarmach, a najsłabsza sieć LSTM przeoczyła "
        f"{lstm_cm['fn']} ataków. Widać więc, że las losowy najlepiej chroni przed "
        "najgroźniejszym błędem, czyli przepuszczeniem ataku, podczas gdy CNN "
        "najskuteczniej ogranicza liczbę niepotrzebnych powiadomień. Różnice te są "
        "jednak niewielkie w stosunku do całkowitej liczby ponad dwudziestu dwóch "
        "tysięcy testowanych połączeń."
    )
    b.figure(FIGURES / "confusion_matrices.png",
             "Rysunek 5. Macierze pomyłek na zbiorze testowym dla wszystkich modeli.",
             width_cm=15.0)

    b.h3("Wydajność i koszt obliczeniowy")
    b.para(
        "Skuteczność to tylko jeden wymiar oceny. W środowisku chmurowym, gdzie "
        "modele są często dotrenowywane i muszą klasyfikować ruch na bieżąco, "
        "kluczowy jest także koszt. Tabela 2 zestawia czasy treningu i inferencji "
        "oraz złożoność modeli."
    )
    headers = ["Model", "Czas treningu [s]", "Czas inferencji [s]", "Złożoność modelu"]
    rows = []
    for k in MODEL_ORDER:
        comp = m[k]["complexity"]
        if "n_parameters" in comp:
            comp_str = f"{thousand(comp['n_parameters'])} param."
        elif "total_tree_nodes" in comp:
            comp_str = (f"{comp['n_estimators']} drzew / "
                        f"{thousand(comp['total_tree_nodes'])} węzłów")
        else:
            comp_str = f"{comp.get('n_coefficients', 0)} wsp."
        rows.append([
            MODEL_PL[k], pl(m[k]["train_time_s"], 2),
            pl(m[k]["inference_time_s"], 4), comp_str,
        ])
    b.table(headers, rows,
            caption="Tabela 2. Wydajność i złożoność modeli.",
            col_widths_cm=[3.2, 3.0, 3.2, 5.0])

    b.para(
        "I tu pojawia się sedno sprawy. Las losowy uczy się w zaledwie kilka "
        "sekund, podczas gdy najlepszy model głęboki potrzebuje kilkudziesięciu "
        "razy więcej czasu, by osiągnąć praktycznie ten sam wynik. Najbardziej "
        "rozbudowana sieć LSTM trenuje się ponad osiem minut, a mimo to wypada "
        "słabiej. Również w fazie działania las losowy i proste modele są wyraźnie "
        "szybsze od sieci CNN i LSTM. Kompromis między kosztem a skutecznością "
        "dobrze obrazuje rysunek 6: najbardziej opłacalne modele leżą w lewej "
        "górnej części wykresu, czyli osiągają wysoką skuteczność przy krótkim "
        "czasie uczenia."
    )
    b.figure(FIGURES / "time_vs_f1.png",
             "Rysunek 6. Kompromis między czasem treningu (skala logarytmiczna) a "
             "skutecznością (F1).",
             width_cm=12.5)

    b.h3("Przebieg uczenia modeli głębokich")
    b.para(
        "Rysunek 7 przedstawia krzywe uczenia modeli głębokich: stratę walidacyjną "
        "oraz ROC-AUC na zbiorze walidacyjnym w kolejnych epokach. Widoczna jest "
        "stabilna zbieżność i działanie mechanizmu wczesnego zatrzymania, który "
        "zapobiega przeuczeniu."
    )
    b.figure(FIGURES / "learning_curves.png",
             "Rysunek 7. Krzywe uczenia modeli głębokich (strata i ROC-AUC "
             "walidacyjny).",
             width_cm=15.0)

    b.h3("Interpretowalność i ważność cech")
    b.para(
        "Dodatkową zaletą lasu losowego jest interpretowalność. Rysunek 8 "
        "przedstawia najważniejsze cechy według miary ważności Giniego. Pozwala to "
        "zidentyfikować, które statystyki połączenia najsilniej różnicują ruch "
        "złośliwy i normalny, co jest cenną informacją dla analityków "
        "bezpieczeństwa, a trudniej dostępną w modelach głębokich działających jak "
        "czarna skrzynka."
    )
    b.figure(FIGURES / "feature_importance.png",
             "Rysunek 8. Najważniejsze cechy według lasu losowego (ważność Giniego).",
             width_cm=12.5)
    b.para(
        "Co ważne, najsilniej różnicujące cechy dotyczą wolumenu i tempa transmisji "
        "oraz statystyk czasu między pakietami, czyli wielkości, które w naturalny "
        "sposób odróżniają zautomatyzowane, masowe działania atakujących od ruchu "
        "generowanego przez człowieka. Zgodność tych obserwacji z intuicją "
        "ekspercką dodatkowo zwiększa zaufanie do modelu i pokazuje, że nie opiera "
        "on swoich decyzji na przypadkowych artefaktach zbioru danych."
    )

    b.h3("Synteza wyników")
    b.para(
        "Podsumowując, zebrane wyniki pozwalają wstępnie odpowiedzieć na postawione "
        "pytania badawcze. Pod względem skuteczności las losowy i najlepsza sieć są "
        "praktycznie nierozróżnialne, przy czym las losowy wykrywa najwięcej ataków. "
        "Pod względem kosztu las losowy jest zdecydowanie tańszy, oferując najlepszą "
        "relację skuteczność do nakładu obliczeniowego. Rozbudowane sieci "
        "sekwencyjne nie przyniosły przewagi, co oznacza, że większa złożoność nie "
        "przełożyła się na lepsze wyniki. Szczegółową interpretację tych obserwacji "
        "w kontekście wdrożeń chmurowych zawiera kolejny rozdział."
    )


def write_dyskusja(b: ReportBuilder, m: dict) -> None:
    b.h2("Dyskusja")

    b.h3("Skuteczność a koszt w realiach chmury")
    b.para(
        "Zestawienie skuteczności i kosztu prowadzi do najważniejszego spostrzeżenia "
        "tej pracy. W warunkach laboratoryjnych można pozwolić sobie na wielogodzinne "
        "treningi, jednak w chmurze sytuacja wygląda inaczej: modele bezpieczeństwa "
        "często wymagają regularnego dotrenowywania na świeżych danych, a czas "
        "obliczeń przekłada się wprost na koszt wynajmowanych zasobów. W tym świetle "
        "model osiągający niemal identyczną skuteczność kilkadziesiąt razy szybciej "
        "jest rozwiązaniem wyraźnie korzystniejszym ekonomicznie. Różnica w jakości "
        "między najlepszą siecią a lasem losowym jest na tyle mała, że w praktyce "
        "trudno ją odróżnić od szumu wynikającego z losowości danych, podczas gdy "
        "różnica w koszcie jest ogromna i jednoznaczna."
    )

    b.h3("Interpretowalność i zaufanie")
    b.para(
        "W bezpieczeństwie liczy się nie tylko trafność decyzji, lecz także "
        "możliwość jej wyjaśnienia. Analityk, który otrzymuje alarm, musi zrozumieć, "
        "dlaczego dane połączenie uznano za złośliwe, aby podjąć właściwą reakcję i "
        "uniknąć ślepego zaufania automatowi. Las losowy ma tu naturalną przewagę: "
        "udostępnia ranking ważności cech i pozwala prześledzić ścieżkę decyzji w "
        "drzewach. Sieci głębokie działają natomiast jak czarna skrzynka i wymagają "
        "dodatkowych, kosztownych technik wyjaśniania. Ten aspekt, choć trudny do "
        "ujęcia w pojedynczej metryce, ma duże znaczenie przy wdrożeniach "
        "produkcyjnych."
    )

    b.h3("Ograniczenia danych tabelarycznych dla sieci głębokich")
    b.para(
        "Uzyskane wyniki wpisują się w szerszą, znaną z literatury obserwację: na "
        "danych w postaci tabeli metody oparte na drzewach pozostają wyjątkowo "
        "konkurencyjne, a sieci głębokie nie wykorzystują swojej największej zalety, "
        "czyli zdolności do uczenia się reprezentacji z danych surowych. Cechy "
        "połączeń sieciowych są już bowiem starannie zaprojektowane przez ekspertów, "
        "więc dodatkowa moc sieci głębokich nie ma tu wiele do odkrycia. Tłumaczy to, "
        "dlaczego rozbudowane architektury sekwencyjne nie przyniosły przewagi, a "
        "najlepiej spośród sieci wypadły rozwiązania prostsze."
    )

    b.h3("Rekomendacje wdrożeniowe")
    b.para(
        "Na podstawie przeprowadzonej analizy można sformułować praktyczne "
        "rekomendacje. Jako domyślny wybór dla systemu wykrywania naruszeń w chmurze "
        "rozsądnie jest przyjąć las losowy: zapewnia on bardzo dobrą skuteczność, "
        "niski koszt treningu i działania, łatwość dotrenowywania oraz "
        "interpretowalność wspierającą pracę analityków. Sieć głęboką warto rozważyć "
        "jako uzupełnienie tam, gdzie priorytetem jest ograniczanie fałszywych "
        "alarmów i gdzie dostępne są akceleratory GPU obniżające koszt treningu. "
        "Niezależnie od wyboru modelu, próg decyzyjny powinien być dostrojony do "
        "polityki bezpieczeństwa: w środowiskach o wysokiej wrażliwości danych "
        "korzystniej jest preferować wyższą czułość kosztem większej liczby alarmów, "
        "natomiast tam, gdzie zespół jest niewielki, większą wagę przykłada się do "
        "precyzji. Dobrą praktyką jest również łączenie modelu uczenia maszynowego z "
        "klasycznymi regułami i monitorowaniem, tak aby decyzja nie opierała się na "
        "pojedynczym źródle."
    )


def write_wnioski(b: ReportBuilder, m: dict) -> None:
    b.h2("Wnioski końcowe")

    best_f1 = max(m, key=lambda k: m[k]["metrics"]["f1"])
    rf = m["Random Forest"]["metrics"]

    b.h3("Podsumowanie")
    b.para(
        "W pracy zrealizowano empiryczne porównanie metod uczenia głębokiego i "
        "lasów losowych w zadaniu prognozowania naruszeń danych w chmurze, "
        "sformułowanym jako klasyfikacja połączeń sieciowych. Zbudowano kompletny, "
        "powtarzalny potok obejmujący przygotowanie danych, trening pięciu modeli "
        "oraz ich ocenę pod kątem skuteczności i kosztu. Najważniejsze wnioski są "
        "następujące:"
    )
    b.bullets([
        "Obie rodziny metod skutecznie wykrywają naruszenia. Zarówno las losowy, "
        "jak i sieci głębokie osiągają wysokie wyniki, wyraźnie przewyższając prosty "
        "model liniowy. Złośliwa aktywność kryje się w złożonych zależnościach "
        "między cechami, które obie metody dobrze wychwytują.",
        f"Skuteczność jest niemal taka sama, ale koszt już nie. Najlepszy model "
        f"głęboki ({best_f1}, F1 = {pl(m[best_f1]['metrics']['f1'])}) i las losowy "
        f"(F1 = {pl(rf['f1'])}) osiągają praktycznie identyczną jakość, przy czym "
        "las losowy dodatkowo wykrywa najwięcej ataków, uczy się kilkadziesiąt razy "
        "szybciej i potrafi wskazać, które cechy zaważyły na decyzji.",
        "Bardziej skomplikowane nie znaczy lepsze. Rozbudowane sieci sekwencyjne, "
        "zwłaszcza LSTM, nie przewyższyły ani lasu losowego, ani prostszej sieci, "
        "generując jedynie wyższy koszt. Potwierdza to obserwację, że dla danych w "
        "postaci tabeli metody oparte na drzewach pozostają bardzo trudne do "
        "pobicia.",
        "Wybór metody zależy od kontekstu. Jeśli liczą się szybkie dotrenowywanie, "
        "niski koszt, dobra wykrywalność i zrozumiałość decyzji, las losowy jest "
        "naturalnym wyborem. Sieci głębokie warto rozważyć tam, gdzie zależy nam na "
        "maksymalnym ograniczeniu fałszywych alarmów i dysponujemy większymi "
        "zasobami obliczeniowymi.",
    ])

    b.h3("Ograniczenia")
    b.para(
        "Wyniki należy interpretować w świetle ograniczeń pracy. Eksperyment "
        "przeprowadzono na losowym wycinku danych ze względu na rozmiar pełnego "
        "zbioru; większa próbka mogłaby nieco zmienić konkretne liczby, choć raczej "
        "nie ogólne wnioski. Nie przeprowadzono również wyczerpującego strojenia "
        "hiperparametrów, lecz użyto rozsądnych wartości domyślnych, jednakowych dla "
        "wszystkich modeli. Obliczenia prowadzono na procesorze; na akceleratorach "
        "GPU względne czasy treningu sieci głębokich uległyby skróceniu, choć "
        "relacja kosztów pozostałaby jakościowo podobna."
    )

    b.h3("Kierunki dalszych prac")
    b.para(
        "Naturalne rozszerzenia obejmują: walidację na pełnym zbiorze "
        "CSE-CIC-IDS2018 oraz innych zbiorach (UNSW-NB15, NSL-KDD); systematyczne "
        "strojenie hiperparametrów i włączenie metod typu gradient boosting "
        "(XGBoost, LightGBM); klasyfikację wieloklasową i wykrywanie nieznanych "
        "ataków; analizę odporności modeli na ataki adwersarialne oraz na dryf "
        "danych; a także integrację najlepszego modelu w architekturze strumieniowej "
        "wraz z mechanizmami wyjaśnialności wspierającymi pracę analityków."
    )

    b.h3("Podsumowanie końcowe")
    b.para(
        "Przeprowadzone badanie pokazuje, że w prognozowaniu naruszeń danych w "
        "chmurze nie ma jednej, bezdyskusyjnie najlepszej metody; wybór jest "
        "kompromisem między skutecznością a kosztem, szybkością i zrozumiałością "
        "decyzji. Dla danych opisujących ruch sieciowy las losowy okazuje się "
        "wyjątkowo silnym i tanim rozwiązaniem, któremu sieci głębokie co najwyżej "
        "dorównują, lecz go nie prześcigają, i to dopiero za cenę znacznie większego "
        "nakładu obliczeniowego. Płynie z tego praktyczny wniosek: zanim sięgnie się "
        "po skomplikowane sieci neuronowe, warto najpierw wypróbować dobrze dobraną "
        "metodę klasyczną."
    )


def write_bibliografia(b: ReportBuilder) -> None:
    b.h2("Bibliografia")
    refs = [
        "Breiman L., Random Forests, Machine Learning, 45(1), 5-32, 2001.",
        "Hochreiter S., Schmidhuber J., Long Short-Term Memory, Neural Computation, "
        "9(8), 1735-1780, 1997.",
        "LeCun Y., Bottou L., Bengio Y., Haffner P., Gradient-Based Learning Applied "
        "to Document Recognition, Proceedings of the IEEE, 86(11), 2278-2324, 1998.",
        "Sharafaldin I., Lashkari A. H., Ghorbani A. A., Toward Generating a New "
        "Intrusion Detection Dataset and Intrusion Traffic Characterization, ICISSP, "
        "108-116, 2018.",
        "Moustafa N., Slay J., UNSW-NB15: A Comprehensive Data Set for Network "
        "Intrusion Detection Systems, MilCIS, 1-6, 2015.",
        "Tavallaee M., Bagheri E., Lu W., Ghorbani A. A., A Detailed Analysis of the "
        "KDD CUP 99 Data Set, IEEE CISDA, 1-6, 2009.",
        "Grinsztajn L., Oyallon E., Varoquaux G., Why Do Tree-Based Models Still "
        "Outperform Deep Learning on Typical Tabular Data?, NeurIPS, 2022.",
        "Goodfellow I., Bengio Y., Courville A., Deep Learning, MIT Press, 2016.",
        "Pedregosa F. i in., Scikit-learn: Machine Learning in Python, JMLR, 12, "
        "2825-2830, 2011.",
        "Paszke A. i in., PyTorch: An Imperative Style, High-Performance Deep "
        "Learning Library, NeurIPS, 2019.",
    ]
    for i, r in enumerate(refs, 1):
        b.para(f"[{i}] {r}", justify=False)


def main() -> None:
    metrics, dataset = load_data()
    b = ReportBuilder(TEMPLATE)
    b.set_work_title(WORK_TITLE)
    b.strip_old_body()

    write_streszczenie(b, metrics, dataset)
    write_wstep(b)
    write_tematyka(b)
    write_problem(b, dataset)
    write_podejscie(b)
    write_realizacja(b, dataset)
    write_implementacja(b)
    write_wyniki(b, metrics)
    write_dyskusja(b, metrics)
    write_wnioski(b, metrics)
    write_bibliografia(b)

    b.finalize(OUTPUT)
    print(f"[docx] Saved report to {OUTPUT}")


if __name__ == "__main__":
    main()
